[2025-09-30T17:48:21.700+0000] {processor.py:161} INFO - Started process (PID=3728) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:48:21.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:48:21.802+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:21.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:22.062+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:22.359+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:22.358+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:dag4
[2025-09-30T17:48:22.392+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:22.391+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:dag4
[2025-09-30T17:48:22.442+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:22.442+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:dag4
[2025-09-30T17:48:22.445+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:22.444+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:48:22.487+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:22.486+0000] {dag.py:3118} INFO - Creating ORM DAG for dag4
[2025-09-30T17:48:22.520+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:22.520+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:47:00+00:00, run_after=2025-09-30 17:48:00+00:00
[2025-09-30T17:48:22.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.944 seconds
[2025-09-30T17:48:25.949+0000] {processor.py:161} INFO - Started process (PID=3737) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:48:25.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:48:25.959+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:25.958+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:26.126+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:26.167+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:26.166+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:48:26.283+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:26.280+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:47:00+00:00, run_after=2025-09-30 17:48:00+00:00
[2025-09-30T17:48:26.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.483 seconds
[2025-09-30T17:48:27.543+0000] {processor.py:161} INFO - Started process (PID=3739) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:48:27.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:48:27.554+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:27.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:27.624+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:27.670+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:27.669+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:48:27.722+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:27.721+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:47:00+00:00, run_after=2025-09-30 17:48:00+00:00
[2025-09-30T17:48:27.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.278 seconds
[2025-09-30T17:48:34.185+0000] {processor.py:161} INFO - Started process (PID=3750) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:48:34.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:48:34.195+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:34.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:34.297+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:34.328+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:34.327+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:48:34.393+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:34.392+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:48:34.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.410 seconds
[2025-09-30T17:48:36.687+0000] {processor.py:161} INFO - Started process (PID=3752) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:48:36.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:48:36.694+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:36.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:36.758+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:36.795+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:36.794+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:48:36.857+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:36.857+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:48:36.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.260 seconds
[2025-09-30T17:48:40.162+0000] {processor.py:161} INFO - Started process (PID=3761) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:48:40.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:48:40.169+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:40.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:40.210+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:48:40.236+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:40.235+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:48:40.281+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:48:40.281+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:48:40.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.177 seconds
[2025-09-30T17:49:10.489+0000] {processor.py:161} INFO - Started process (PID=3813) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:49:10.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:49:10.495+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:10.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:10.536+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:10.758+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:10.757+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:49:10.800+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:10.799+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:49:10.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.363 seconds
[2025-09-30T17:49:25.706+0000] {processor.py:161} INFO - Started process (PID=3849) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:49:25.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:49:25.714+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:25.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:25.902+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:25.925+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:25.924+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:49:25.990+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:25.989+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:49:26.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.444 seconds
[2025-09-30T17:49:27.211+0000] {processor.py:161} INFO - Started process (PID=3852) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:49:27.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:49:27.217+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:27.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:27.261+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:27.284+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:27.283+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:49:27.317+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:27.317+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:49:27.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.153 seconds
[2025-09-30T17:49:31.684+0000] {processor.py:161} INFO - Started process (PID=3855) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:49:31.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:49:31.690+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:31.689+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:31.731+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:31.751+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:31.750+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:49:31.789+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:31.788+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:49:31.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.167 seconds
[2025-09-30T17:49:41.100+0000] {processor.py:161} INFO - Started process (PID=3872) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:49:41.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:49:41.109+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:41.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:41.150+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:41.184+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:41.183+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:49:41.222+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:41.221+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:49:41.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.183 seconds
[2025-09-30T17:49:45.241+0000] {processor.py:161} INFO - Started process (PID=3881) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:49:45.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:49:45.246+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:45.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:45.292+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:49:45.330+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:45.330+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:49:45.362+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:49:45.362+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:40:00+00:00, run_after=2025-09-30 17:45:00+00:00
[2025-09-30T17:49:45.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.167 seconds
[2025-09-30T17:50:15.464+0000] {processor.py:161} INFO - Started process (PID=3939) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:50:15.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:50:15.469+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:50:15.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:50:15.513+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:50:15.553+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:50:15.552+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:50:15.593+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:50:15.593+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:50:15.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.198 seconds
[2025-09-30T17:50:45.727+0000] {processor.py:161} INFO - Started process (PID=3994) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:50:45.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:50:45.732+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:50:45.731+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:50:45.756+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:50:45.789+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:50:45.788+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:50:45.838+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:50:45.837+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:50:45.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.260 seconds
[2025-09-30T17:51:16.346+0000] {processor.py:161} INFO - Started process (PID=4046) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:51:16.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:51:16.353+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:51:16.352+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:51:16.384+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:51:16.416+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:51:16.415+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:51:16.449+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:51:16.449+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:51:16.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.185 seconds
[2025-09-30T17:51:48.059+0000] {processor.py:161} INFO - Started process (PID=4101) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:51:48.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:51:48.120+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:51:48.114+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:51:48.508+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:51:48.658+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:51:48.645+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:51:48.802+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:51:48.801+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:51:48.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.972 seconds
[2025-09-30T17:52:19.178+0000] {processor.py:161} INFO - Started process (PID=4156) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:52:19.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:52:19.184+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:52:19.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:52:19.220+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:52:19.262+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:52:19.261+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:52:19.334+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:52:19.333+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:52:19.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.261 seconds
[2025-09-30T17:52:49.598+0000] {processor.py:161} INFO - Started process (PID=4211) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:52:49.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:52:49.603+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:52:49.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:52:49.634+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:52:49.666+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:52:49.665+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:52:49.702+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:52:49.701+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:52:49.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.161 seconds
[2025-09-30T17:53:20.227+0000] {processor.py:161} INFO - Started process (PID=4266) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:53:20.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:53:20.236+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:20.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:53:20.274+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:53:20.328+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:20.327+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:53:20.389+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:20.388+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:53:20.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.224 seconds
[2025-09-30T17:53:35.975+0000] {processor.py:161} INFO - Started process (PID=4300) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:53:35.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:53:35.982+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:35.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:53:36.041+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:53:36.090+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:36.089+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:53:36.138+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:36.137+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:53:36.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.264 seconds
[2025-09-30T17:53:59.081+0000] {processor.py:161} INFO - Started process (PID=4342) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:53:59.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:53:59.090+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:59.089+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:53:59.146+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:53:59.194+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:59.194+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:53:59.240+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:53:59.239+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:53:59.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.309 seconds
[2025-09-30T17:54:05.831+0000] {processor.py:161} INFO - Started process (PID=4356) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:05.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:05.847+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:05.846+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:05.911+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:05.898+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 13
    with open()
               ^
SyntaxError: expected ':'
[2025-09-30T17:54:05.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:06.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.188 seconds
[2025-09-30T17:54:10.183+0000] {processor.py:161} INFO - Started process (PID=4358) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:10.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:10.198+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:10.197+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:10.242+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:10.240+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 14
    cursor.close()    
    ^^^^^^
IndentationError: expected an indented block after 'with' statement on line 13
[2025-09-30T17:54:10.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:10.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.148 seconds
[2025-09-30T17:54:14.674+0000] {processor.py:161} INFO - Started process (PID=4361) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:14.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:14.681+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:14.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:14.710+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:14.707+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 14
    cursor.close()    
    ^^^^^^
IndentationError: expected an indented block after 'with' statement on line 13
[2025-09-30T17:54:14.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:14.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.122 seconds
[2025-09-30T17:54:16.803+0000] {processor.py:161} INFO - Started process (PID=4367) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:16.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:16.810+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:16.810+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:16.857+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:16.854+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 13
    with open(tasks_data.txt', 'w') as f:
                                 ^
SyntaxError: unterminated string literal (detected at line 13)
[2025-09-30T17:54:16.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:16.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.178 seconds
[2025-09-30T17:54:17.992+0000] {processor.py:161} INFO - Started process (PID=4373) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:18.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:18.008+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:18.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:18.039+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:18.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 14
    cursor.close()    
    ^^^^^^
IndentationError: expected an indented block after 'with' statement on line 13
[2025-09-30T17:54:18.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:18.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.138 seconds
[2025-09-30T17:54:22.388+0000] {processor.py:161} INFO - Started process (PID=4383) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:22.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:22.399+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:22.395+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:22.429+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:22.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 15
    cursor.close()    
    ^^^^^^
IndentationError: expected an indented block after 'with' statement on line 13
[2025-09-30T17:54:22.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:22.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.098 seconds
[2025-09-30T17:54:28.298+0000] {processor.py:161} INFO - Started process (PID=4393) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:28.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:28.308+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:28.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:28.425+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:28.422+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 14
    for data in 
                ^
SyntaxError: invalid syntax
[2025-09-30T17:54:28.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:28.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.251 seconds
[2025-09-30T17:54:32.132+0000] {processor.py:161} INFO - Started process (PID=4402) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:32.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:32.143+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:32.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:32.232+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:32.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 14
    for data in tasks
                     ^
SyntaxError: expected ':'
[2025-09-30T17:54:32.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:32.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.250 seconds
[2025-09-30T17:54:36.806+0000] {processor.py:161} INFO - Started process (PID=4413) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:36.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:36.837+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:36.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:36.953+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:37.011+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:37.010+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:54:37.106+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:37.106+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:54:37.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.449 seconds
[2025-09-30T17:54:40.119+0000] {processor.py:161} INFO - Started process (PID=4420) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:40.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:40.134+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:40.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:40.210+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:40.278+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:40.277+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:54:40.405+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:40.404+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:54:40.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.384 seconds
[2025-09-30T17:54:41.464+0000] {processor.py:161} INFO - Started process (PID=4421) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:41.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:41.474+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:41.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:41.531+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:41.579+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:41.578+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:54:41.645+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:41.644+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:54:41.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.302 seconds
[2025-09-30T17:54:54.849+0000] {processor.py:161} INFO - Started process (PID=4443) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:54.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:54.856+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:54.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:54.903+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:54.945+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:54.944+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:54:54.982+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:54.982+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:54:55.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.182 seconds
[2025-09-30T17:54:57.139+0000] {processor.py:161} INFO - Started process (PID=4448) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:54:57.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:54:57.145+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:57.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:57.189+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:54:57.221+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:57.220+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:54:57.256+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:54:57.256+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:50:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:54:57.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.165 seconds
[2025-09-30T17:55:05.880+0000] {processor.py:161} INFO - Started process (PID=4468) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:55:05.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:55:05.898+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:05.886+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:55:06.062+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:55:06.505+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:06.502+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:55:06.566+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:06.566+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:54:00+00:00, run_after=2025-09-30 17:55:00+00:00
[2025-09-30T17:55:06.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.795 seconds
[2025-09-30T17:55:37.184+0000] {processor.py:161} INFO - Started process (PID=4523) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:55:37.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:55:37.194+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:37.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:55:37.241+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:55:37.298+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:37.297+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:55:37.350+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:37.349+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:55:00+00:00, run_after=2025-09-30 17:56:00+00:00
[2025-09-30T17:55:37.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.293 seconds
[2025-09-30T17:55:49.597+0000] {processor.py:161} INFO - Started process (PID=4542) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:55:49.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:55:49.604+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:49.603+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:55:49.663+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:55:49.722+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:49.721+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:55:49.836+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:55:49.836+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:55:00+00:00, run_after=2025-09-30 17:56:00+00:00
[2025-09-30T17:55:49.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.310 seconds
[2025-09-30T17:56:20.428+0000] {processor.py:161} INFO - Started process (PID=4595) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:56:20.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:56:20.437+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:56:20.436+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:56:20.489+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:56:20.537+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:56:20.536+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:56:20.589+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:56:20.588+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:56:00+00:00, run_after=2025-09-30 17:57:00+00:00
[2025-09-30T17:56:20.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.225 seconds
[2025-09-30T17:56:50.759+0000] {processor.py:161} INFO - Started process (PID=4650) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:56:50.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:56:50.766+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:56:50.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:56:50.813+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:56:50.861+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:56:50.860+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:56:50.911+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:56:50.910+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:56:00+00:00, run_after=2025-09-30 17:57:00+00:00
[2025-09-30T17:56:50.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.222 seconds
[2025-09-30T17:57:22.173+0000] {processor.py:161} INFO - Started process (PID=4705) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:57:22.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:57:22.190+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:22.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:22.494+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:22.602+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:22.593+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:57:22.701+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:22.701+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:57:00+00:00, run_after=2025-09-30 17:58:00+00:00
[2025-09-30T17:57:22.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.632 seconds
[2025-09-30T17:57:50.047+0000] {processor.py:161} INFO - Started process (PID=4756) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:57:50.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:57:50.053+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:50.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:50.094+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:50.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 4
    from air
            ^
SyntaxError: invalid syntax
[2025-09-30T17:57:50.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:50.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.110 seconds
[2025-09-30T17:57:52.974+0000] {processor.py:161} INFO - Started process (PID=4761) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:57:52.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:57:52.980+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:52.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:53.094+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:53.186+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:53.184+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:57:53.255+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:53.252+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:57:00+00:00, run_after=2025-09-30 17:58:00+00:00
[2025-09-30T17:57:53.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.411 seconds
[2025-09-30T17:57:55.292+0000] {processor.py:161} INFO - Started process (PID=4768) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:57:55.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:57:55.299+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:55.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:55.327+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:57:55.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 4
    from airflow.operators. import BranchPythonOperator
                            ^^^^^^
SyntaxError: invalid syntax
[2025-09-30T17:57:55.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:57:55.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.128 seconds
[2025-09-30T17:58:01.428+0000] {processor.py:161} INFO - Started process (PID=4780) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:01.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:01.435+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:01.434+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:01.490+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:01.484+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 4, in <module>
    from airflow.operators.email_ import BranchPythonOperator
ModuleNotFoundError: No module named 'airflow.operators.email_'
[2025-09-30T17:58:01.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:01.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.159 seconds
[2025-09-30T17:58:02.735+0000] {processor.py:161} INFO - Started process (PID=4783) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:02.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:02.745+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:02.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:02.793+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:02.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 4, in <module>
    from airflow.operators.email_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.email_operator' (unknown location)
[2025-09-30T17:58:02.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:02.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.112 seconds
[2025-09-30T17:58:06.854+0000] {processor.py:161} INFO - Started process (PID=4792) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:06.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:06.863+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:06.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:06.909+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:06.902+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 4, in <module>
    from airflow.operators.email_operator import Email
ImportError: cannot import name 'Email' from 'airflow.operators.email_operator' (unknown location)
[2025-09-30T17:58:06.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:06.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.123 seconds
[2025-09-30T17:58:09.089+0000] {processor.py:161} INFO - Started process (PID=4794) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:09.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:09.097+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:09.097+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:09.163+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:09.202+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:09.201+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:58:09.248+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:09.248+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:57:00+00:00, run_after=2025-09-30 17:58:00+00:00
[2025-09-30T17:58:09.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.262 seconds
[2025-09-30T17:58:38.101+0000] {processor.py:161} INFO - Started process (PID=4847) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:38.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:38.108+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:38.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:38.578+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:38.647+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:38.646+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T17:58:38.727+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:38.726+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 17:58:00+00:00, run_after=2025-09-30 17:59:00+00:00
[2025-09-30T17:58:38.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.797 seconds
[2025-09-30T17:58:49.306+0000] {processor.py:161} INFO - Started process (PID=4869) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:49.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:49.338+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:49.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:49.910+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:49.830+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 471, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'html_content', 'subject', 'to'
[2025-09-30T17:58:49.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:50.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.812 seconds
[2025-09-30T17:58:52.059+0000] {processor.py:161} INFO - Started process (PID=4871) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:52.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:52.086+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:52.085+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:52.390+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:52.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 35, in <module>
    task_
NameError: name 'task_' is not defined
[2025-09-30T17:58:52.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:52.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.447 seconds
[2025-09-30T17:58:56.900+0000] {processor.py:161} INFO - Started process (PID=4878) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:58:56.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:58:56.922+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:56.921+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:57.092+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:58:57.025+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 471, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'html_content', 'subject', 'to'
[2025-09-30T17:58:57.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:58:57.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.314 seconds
[2025-09-30T17:59:00.804+0000] {processor.py:161} INFO - Started process (PID=4885) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:00.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:00.832+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:00.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:01.660+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:01.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to =
    ^^^^
SyntaxError: expected argument value expression
[2025-09-30T17:59:01.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:01.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.089 seconds
[2025-09-30T17:59:05.247+0000] {processor.py:161} INFO - Started process (PID=4895) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:05.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:05.300+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:05.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:05.351+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:05.349+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = 
    ^^^^
SyntaxError: expected argument value expression
[2025-09-30T17:59:05.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:05.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.401 seconds
[2025-09-30T17:59:07.968+0000] {processor.py:161} INFO - Started process (PID=4904) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:07.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:07.975+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:07.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:08.038+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:08.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = =abdu 
         ^
SyntaxError: invalid syntax
[2025-09-30T17:59:08.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:08.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.177 seconds
[2025-09-30T17:59:09.704+0000] {processor.py:161} INFO - Started process (PID=4909) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:09.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:09.804+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:09.803+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:09.861+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:09.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = = "" 
         ^
SyntaxError: invalid syntax
[2025-09-30T17:59:09.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:09.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.240 seconds
[2025-09-30T17:59:25.190+0000] {processor.py:161} INFO - Started process (PID=4931) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:25.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:25.202+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:25.200+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:25.417+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:25.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 40
    )
    ^
SyntaxError: unmatched ')'
[2025-09-30T17:59:25.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:25.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.303 seconds
[2025-09-30T17:59:31.577+0000] {processor.py:161} INFO - Started process (PID=4944) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:31.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:31.584+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:31.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:31.607+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:31.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:31.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:31.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.097 seconds
[2025-09-30T17:59:35.364+0000] {processor.py:161} INFO - Started process (PID=4954) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:35.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:35.369+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:35.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:35.430+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:35.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:35.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:35.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.135 seconds
[2025-09-30T17:59:36.771+0000] {processor.py:161} INFO - Started process (PID=4957) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:36.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:36.775+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:36.774+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:36.797+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:36.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:36.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:36.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.078 seconds
[2025-09-30T17:59:39.301+0000] {processor.py:161} INFO - Started process (PID=4966) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:39.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:39.306+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:39.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:39.328+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:39.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:39.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:39.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.074 seconds
[2025-09-30T17:59:43.147+0000] {processor.py:161} INFO - Started process (PID=4973) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:43.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:43.154+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:43.153+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:43.188+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:43.185+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    html_content = """ 
                   ^
SyntaxError: unterminated triple-quoted string literal (detected at line 40)
[2025-09-30T17:59:43.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:43.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.096 seconds
[2025-09-30T17:59:48.827+0000] {processor.py:161} INFO - Started process (PID=4987) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:48.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:48.883+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:48.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:48.941+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:48.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:48.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:49.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.235 seconds
[2025-09-30T17:59:50.738+0000] {processor.py:161} INFO - Started process (PID=4990) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:50.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:50.758+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:50.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:50.987+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:50.984+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:50.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:51.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.337 seconds
[2025-09-30T17:59:52.291+0000] {processor.py:161} INFO - Started process (PID=4993) to work on /opt/airflow/dags/dag4.py
[2025-09-30T17:59:52.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T17:59:52.296+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:52.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:52.318+0000] {logging_mixin.py:188} INFO - [2025-09-30T17:59:52.315+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T17:59:52.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T17:59:52.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.125 seconds
[2025-09-30T18:00:07.390+0000] {processor.py:161} INFO - Started process (PID=5017) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:07.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:07.394+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:07.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:07.417+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:07.415+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:07.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:07.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.080 seconds
[2025-09-30T18:00:10.664+0000] {processor.py:161} INFO - Started process (PID=5027) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:10.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:10.667+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:10.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:10.691+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:10.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:10.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:10.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.081 seconds
[2025-09-30T18:00:15.341+0000] {processor.py:161} INFO - Started process (PID=5036) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:15.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:15.345+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:15.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:15.378+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:15.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:15.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:15.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.095 seconds
[2025-09-30T18:00:15.612+0000] {processor.py:161} INFO - Started process (PID=5038) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:15.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:15.615+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:15.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:15.637+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:15.635+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:15.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:15.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.074 seconds
[2025-09-30T18:00:23.028+0000] {processor.py:161} INFO - Started process (PID=5052) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:23.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:23.034+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:23.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:23.060+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:23.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:23.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:23.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.085 seconds
[2025-09-30T18:00:30.812+0000] {processor.py:161} INFO - Started process (PID=5059) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:30.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:30.816+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:30.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:30.843+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:30.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:30.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:30.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.104 seconds
[2025-09-30T18:00:37.890+0000] {processor.py:161} INFO - Started process (PID=5070) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:37.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:37.905+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:37.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:37.958+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:37.948+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:37.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:38.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.168 seconds
[2025-09-30T18:00:40.287+0000] {processor.py:161} INFO - Started process (PID=5078) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:40.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:40.291+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:40.291+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:40.324+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:40.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:40.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:40.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.302 seconds
[2025-09-30T18:00:42.596+0000] {processor.py:161} INFO - Started process (PID=5088) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:42.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:42.603+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:42.602+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:42.696+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:42.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = ""
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:42.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:42.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.240 seconds
[2025-09-30T18:00:53.521+0000] {processor.py:161} INFO - Started process (PID=5111) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:53.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:53.529+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:53.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:53.571+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:53.568+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    to = "abdullah.elmogy@gmail.com"
         ^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:00:53.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:53.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.121 seconds
[2025-09-30T18:00:56.574+0000] {processor.py:161} INFO - Started process (PID=5112) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:00:56.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:00:56.578+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:56.578+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:56.633+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:00:56.625+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:00:56.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:00:56.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.117 seconds
[2025-09-30T18:01:24.286+0000] {processor.py:161} INFO - Started process (PID=5155) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:01:24.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:01:24.301+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:01:24.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:01:24.850+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:01:24.528+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:01:24.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:01:25.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.772 seconds
[2025-09-30T18:01:30.238+0000] {processor.py:161} INFO - Started process (PID=5168) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:01:30.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:01:30.276+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:01:30.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:01:31.575+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:01:31.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:01:31.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:01:31.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.576 seconds
[2025-09-30T18:01:40.242+0000] {processor.py:161} INFO - Started process (PID=5187) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:01:40.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:01:40.257+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:01:40.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:01:40.493+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:01:40.381+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:01:40.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:01:40.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.369 seconds
[2025-09-30T18:02:11.988+0000] {processor.py:161} INFO - Started process (PID=5240) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:02:11.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:02:12.005+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:02:12.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:02:12.163+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:02:12.121+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 36, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:02:12.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:02:12.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.287 seconds
[2025-09-30T18:05:41.662+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:05:41.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:05:41.717+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:05:41.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:05:42.034+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:05:41.983+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:05:42.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:05:42.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.874 seconds
[2025-09-30T18:06:52.286+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:06:52.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:06:52.376+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:06:52.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:06:52.717+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:06:52.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:06:52.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:06:53.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.768 seconds
[2025-09-30T18:07:11.076+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:07:11.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:07:11.125+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:07:11.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:07:11.705+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:07:11.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:07:11.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:07:12.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.980 seconds
[2025-09-30T18:07:22.286+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:07:22.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:07:22.309+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:07:22.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:07:23.908+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:07:23.470+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:07:23.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:07:24.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.796 seconds
[2025-09-30T18:07:57.003+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:07:57.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:07:57.019+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:07:57.019+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:07:57.150+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:07:57.113+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:07:57.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:07:57.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.255 seconds
[2025-09-30T18:08:28.947+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:08:28.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:08:28.982+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:08:28.981+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:08:29.479+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:08:29.448+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:08:29.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:08:29.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.765 seconds
[2025-09-30T18:09:01.246+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:09:01.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:09:01.259+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:09:01.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:09:01.524+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:09:01.466+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:09:01.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:09:01.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.420 seconds
[2025-09-30T18:09:32.336+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:09:32.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:09:32.370+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:09:32.369+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:09:32.492+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:09:32.472+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:09:32.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:09:32.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.349 seconds
[2025-09-30T18:10:03.482+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:10:03.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:10:03.509+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:10:03.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:10:03.752+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:10:03.642+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:10:03.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:10:03.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.462 seconds
[2025-09-30T18:10:35.326+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:10:35.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:10:35.358+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:10:35.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:10:35.472+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:10:35.456+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 34, in <module>
    task_mail = EmailOperator(
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'html_content'
[2025-09-30T18:10:35.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:10:35.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.270 seconds
[2025-09-30T18:11:08.245+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:11:08.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:11:08.281+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:08.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:09.790+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:09.787+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    html_conte
    ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:11:09.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:09.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.763 seconds
[2025-09-30T18:11:15.576+0000] {processor.py:161} INFO - Started process (PID=495) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:11:15.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:11:15.652+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:15.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:16.069+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:16.067+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 39
    files = [output_file], 
          ^
SyntaxError: invalid syntax
[2025-09-30T18:11:16.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:16.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.693 seconds
[2025-09-30T18:11:24.283+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:11:24.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:11:24.308+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:24.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:25.316+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:25.313+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    html_content ='<h3> '
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:11:25.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:25.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.206 seconds
[2025-09-30T18:11:31.411+0000] {processor.py:161} INFO - Started process (PID=519) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:11:31.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:11:31.442+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:31.441+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:31.608+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:31.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag4.py", line 38
    html_content ='<h3> This is data about the task <>'
                  
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-09-30T18:11:31.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:31.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.350 seconds
[2025-09-30T18:11:36.060+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:11:36.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:11:36.088+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:36.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:37.250+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:11:38.547+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:38.545+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:dag4
[2025-09-30T18:11:38.678+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:38.677+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:dag4
[2025-09-30T18:11:39.039+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:39.038+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:dag4
[2025-09-30T18:11:39.043+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:39.041+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:11:39.111+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:39.110+0000] {dag.py:3118} INFO - Creating ORM DAG for dag4
[2025-09-30T18:11:39.172+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:11:39.171+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:00:00+00:00, run_after=2025-09-30 18:10:00+00:00
[2025-09-30T18:11:39.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 3.433 seconds
[2025-09-30T18:12:25.566+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:12:25.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:12:25.600+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:12:25.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:12:26.231+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:12:26.411+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:12:26.409+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:12:26.619+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:12:26.619+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:00:00+00:00, run_after=2025-09-30 18:10:00+00:00
[2025-09-30T18:12:26.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.280 seconds
[2025-09-30T18:12:57.320+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:12:57.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:12:57.339+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:12:57.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:12:57.417+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:12:57.516+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:12:57.515+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:12:57.668+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:12:57.667+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:12:57.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.501 seconds
[2025-09-30T18:13:28.037+0000] {processor.py:161} INFO - Started process (PID=687) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:13:28.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:13:28.053+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:13:28.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:13:28.158+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:13:28.258+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:13:28.257+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:13:28.418+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:13:28.418+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:13:28.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.533 seconds
[2025-09-30T18:13:58.764+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:13:58.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:13:58.780+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:13:58.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:13:58.890+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:13:58.986+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:13:58.985+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:13:59.087+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:13:59.087+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:13:59.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.451 seconds
[2025-09-30T18:14:29.686+0000] {processor.py:161} INFO - Started process (PID=797) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:14:29.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:14:29.712+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:14:29.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:14:29.842+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:14:29.956+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:14:29.955+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:14:30.118+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:14:30.118+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:14:30.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.571 seconds
[2025-09-30T18:15:00.639+0000] {processor.py:161} INFO - Started process (PID=851) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:15:00.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:15:00.662+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:15:00.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:15:00.852+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:15:00.952+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:15:00.951+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:15:01.086+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:15:01.085+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:15:01.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.691 seconds
[2025-09-30T18:15:33.017+0000] {processor.py:161} INFO - Started process (PID=906) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:15:33.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:15:33.034+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:15:33.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:15:33.120+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:15:33.245+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:15:33.244+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:15:33.390+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:15:33.390+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:15:33.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.527 seconds
[2025-09-30T18:16:04.774+0000] {processor.py:161} INFO - Started process (PID=962) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:16:04.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:16:04.790+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:16:04.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:16:04.921+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:16:05.032+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:16:05.031+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:16:05.145+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:16:05.145+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:16:05.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.501 seconds
[2025-09-30T18:16:35.550+0000] {processor.py:161} INFO - Started process (PID=1018) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:16:35.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:16:35.557+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:16:35.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:16:35.696+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:16:35.788+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:16:35.787+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:16:35.914+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:16:35.913+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:16:36.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.514 seconds
[2025-09-30T18:17:06.381+0000] {processor.py:161} INFO - Started process (PID=1073) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:17:06.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:17:06.394+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:17:06.394+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:17:06.682+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:17:06.798+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:17:06.789+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:17:06.932+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:17:06.932+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:17:07.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.687 seconds
[2025-09-30T18:17:37.981+0000] {processor.py:161} INFO - Started process (PID=1127) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:17:37.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:17:37.985+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:17:37.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:17:38.113+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:17:38.218+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:17:38.207+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:17:38.334+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:17:38.333+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:17:38.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.539 seconds
[2025-09-30T18:18:08.667+0000] {processor.py:161} INFO - Started process (PID=1181) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:18:08.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:18:08.685+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:18:08.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:18:08.811+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:18:08.885+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:18:08.884+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:18:09.016+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:18:09.015+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:18:09.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.492 seconds
[2025-09-30T18:18:39.605+0000] {processor.py:161} INFO - Started process (PID=1237) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:18:39.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:18:39.610+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:18:39.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:18:39.702+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:18:39.804+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:18:39.803+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:18:39.960+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:18:39.960+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:18:40.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.505 seconds
[2025-09-30T18:19:10.851+0000] {processor.py:161} INFO - Started process (PID=1293) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:19:10.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:19:10.865+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:19:10.856+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:19:11.017+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:19:11.130+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:19:11.129+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:19:11.246+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:19:11.246+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:19:11.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.534 seconds
[2025-09-30T18:19:41.663+0000] {processor.py:161} INFO - Started process (PID=1348) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:19:41.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:19:41.676+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:19:41.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:19:41.776+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:19:41.875+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:19:41.873+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:19:42.016+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:19:42.015+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:10:00+00:00, run_after=2025-09-30 18:20:00+00:00
[2025-09-30T18:19:42.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.492 seconds
[2025-09-30T18:20:13.043+0000] {processor.py:161} INFO - Started process (PID=1404) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:20:13.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:20:13.049+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:20:13.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:20:13.167+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:20:13.276+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:20:13.275+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:20:13.437+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:20:13.436+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:20:13.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.508 seconds
[2025-09-30T18:20:44.102+0000] {processor.py:161} INFO - Started process (PID=1459) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:20:44.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:20:44.114+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:20:44.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:20:44.199+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:20:44.313+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:20:44.302+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:20:45.214+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:20:45.213+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:20:45.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.233 seconds
[2025-09-30T18:21:15.885+0000] {processor.py:161} INFO - Started process (PID=1514) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:21:15.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:21:15.903+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:15.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:21:16.002+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:21:16.081+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:16.081+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:21:16.214+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:16.214+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:21:16.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.002 seconds
[2025-09-30T18:21:37.847+0000] {processor.py:161} INFO - Started process (PID=1550) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:21:37.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:21:37.863+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:37.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:21:38.073+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:21:38.173+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:38.172+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:21:38.302+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:38.302+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:21:38.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.634 seconds
[2025-09-30T18:21:43.667+0000] {processor.py:161} INFO - Started process (PID=1561) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:21:43.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:21:43.747+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:43.746+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:21:44.260+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:21:44.489+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:44.488+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:21:44.612+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:21:44.611+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:21:44.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.094 seconds
[2025-09-30T18:22:15.858+0000] {processor.py:161} INFO - Started process (PID=1611) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:22:15.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:22:15.894+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:22:15.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:22:16.223+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:22:16.331+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:22:16.321+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:22:16.484+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:22:16.483+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:22:16.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 0.772 seconds
[2025-09-30T18:22:48.577+0000] {processor.py:161} INFO - Started process (PID=1660) to work on /opt/airflow/dags/dag4.py
[2025-09-30T18:22:48.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag4.py for tasks to queue
[2025-09-30T18:22:48.600+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:22:48.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag4.py
[2025-09-30T18:22:48.742+0000] {processor.py:840} INFO - DAG(s) 'dag4' retrieved from /opt/airflow/dags/dag4.py
[2025-09-30T18:22:48.839+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:22:48.838+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-09-30T18:22:49.470+0000] {logging_mixin.py:188} INFO - [2025-09-30T18:22:49.469+0000] {dag.py:3954} INFO - Setting next_dagrun for dag4 to 2025-09-30 18:20:00+00:00, run_after=2025-09-30 18:30:00+00:00
[2025-09-30T18:22:49.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag4.py took 1.034 seconds
